### ISSUE TITLE
support for other input methods

### ISSUE THREAD

**Issue by macgyver** [gabrielbull/react-aim#2]
Just an idle thought, but have you considered how this might be expanded to support input methods besides the pointer? A keyboard user tabbing inexorably towards a target might be a good indicator of their intent..

**Comment by eliagrady** [comment]
The menuAim is famous for solving **user intent** where it's not clear, such with mouse moves, it has many 'points' which can cause the destination to become invalid by the time the user has moved there with his cursor.

This is not applicable with keyboard, as each keystroke is self-contained and well defined in terms of component logic. Basically, you can create a simple, deterministic automaton to determine the state of your component based on the sequence of keystrokes.

**Comment by gabrielbull** [comment]
@eliagrady explained it well. I will close this issue to keep the focus of this library on the mouse.
