### ISSUE TITLE
Bugfix to calculating top location of a subnav that is higher on the page than parent

### ISSUE THREAD

**Issue by nathanyarnold** [gabrielbull/react-aim#6]
https://github.com/gabrielbull/react-aim/blob/510dba1332151040810de444c430454143e3c152/src/corners.js#L16

We've seen a bug where when a sub-nav is located higher on the page than the parent, the aim target isn't calculated correctly and `onMouseEnter` fires on all the parent siblings. This fixes that:

Change line 16 of `corners.js` to:

`ver = inside(source.top, target.top, source.top + target.height);`

And everything works as intended.

**Comment by gabrielbull** [comment]
Hello @nathanyarnold . Please submit a PR and I will release the bug fix. Thanks for your help!

**Comment by nathanyarnold** [comment]
hi @gabrielbull -- OK, done! Thanks
